name: Deploy .NET App to Azure

on:
  push:
    branches:
      - main  # Runs when code is pushed to the main branch

jobs:
  deploy:
    name: Deploy .NET 8 App to Azure
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # ✅ Setup .NET 8 SDK (Fully Supported)
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0'

      # ✅ Restore Dependencies
      - name: Restore Dependencies
        run: dotnet restore

      # ✅ Build .NET 8 Application
      - name: Build Application
        run: dotnet build --configuration Release --no-restore

      # ✅ Publish .NET 8 Application
      - name: Publish Application
        run: dotnet publish -c Release -o app

      # ✅ Azure Login
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # ✅ Deploy to Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: "uniquewebappnamerabbani"  # Replace with your actual Azure Web App name
          package: ./app
