name: Deploy .NET 9 App to Azure

on:
  push:
    branches:
      - main  # Triggers when code is pushed to the main branch

jobs:
  deploy:
    name: Deploy .NET 9 App to Azure
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # ✅ Setup .NET Core SDK
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.100-preview.4'  # Use the appropriate .NET 9 version

      # ✅ Restore Dependencies
      - name: Restore Dependencies
        run: dotnet restore

      # ✅ Build .NET 9 Application
      - name: Build Application
        run: dotnet build --configuration Release --no-restore

      # ✅ Publish .NET 9 Application
      - name: Publish Application
        run: dotnet publish -c Release -o app

      # ✅ Azure Login
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # ✅ Deploy to Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: "uniquewebappnamerabbani"
          package: ./app
