name: Deploy .NET 9 App to Azure

on:
  push:
    branches:
      - main  # Triggers when code is pushed to the main branch

jobs:
  deploy:
    name: Deploy .NET 9 App to Azure
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # ✅ Download and Install .NET 9 (Latest Preview)
      - name: Install .NET 9 SDK Preview
        run: |
          DOTNET_SDK_VERSION="9.0.100-preview.4"
          DOTNET_INSTALL_DIR="/usr/share/dotnet"
          mkdir -p $DOTNET_INSTALL_DIR
          
          wget -O dotnet-install.sh https://dot.net/v1/dotnet-install.sh
          chmod +x dotnet-install.sh
          ./dotnet-install.sh --install-dir $DOTNET_INSTALL_DIR --version $DOTNET_SDK_VERSION --runtime dotnet

          echo "DOTNET_ROOT=$DOTNET_INSTALL_DIR" >> $GITHUB_ENV
          echo "$DOTNET_INSTALL_DIR" >> $GITHUB_PATH

      # ✅ Setup .NET 9 SDK
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.100-preview.4'

      # ✅ Restore Dependencies
      - name: Restore Dependencies
        run: dotnet restore

      # ✅ Build .NET 9 Application
      - name: Build Application
        run: dotnet build --configuration Release --no-restore

      # ✅ Publish .NET 9 Application
      - name: Publish Application
        run: dotnet publish -c Release -o app

      # ✅ Azure Login
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # ✅ Deploy to Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: "uniquewebappnamerabbani"
          package: ./app
